blog/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views


app_name = 'blog'
urlpatterns = [
    path('register', views.register, name='register'),
    path('login', views.user_login, name='login'),
    path('create/', views.create_post, name='create_post'),
    path('view/<int:post_id>/', views.post_detail, name='view_post'),
    path('delete/<int:post_id>/', views.delete_post, name='delete_post'),
    path('edit/<int:post_id>/', views.edit_post, name='edit_post'),
    path('logout', auth_views.LogoutView.as_view(), name='logout'),
    path('create_categ/', views.create_category, name='create_category'),
]

reluxx_project/urls.py
from django.contrib import admin
from django.urls import path, include

from blog import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('login/', views.user_login, name='login'),
    path('', views.home, name='home'),
]

blog/models.py
from django.contrib.auth.models import User
from django.db import models


class Category(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Post(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField(max_length=500)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='posts')
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='posts')

    def __str__(self):
        return self.title

blog/forms.py
from django import forms

from blog.models import Post, Category


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'content', 'user', 'category')
        # widgets = forms = {
        #     'category': forms.Select(choices=Post.CATEGORY_CHOICES),
        # }


class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ('name',)

blog/views.py
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.forms import UserCreationForm

from blog.forms import PostForm, CategoryForm
from blog.models import Post, Category


# Create your views here.
def register(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('login')
    else:
        form = UserCreationForm()
    return render(request, 'register.html', {'form': form})


def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user=user)
            return redirect('home')
        else:
            error_message = 'Invalid username or password.'
            return render(request, 'login.html', {'error_message': error_message})
    return render(request, 'login.html')


def home(request):
    category = request.GET.get('category')
    query = request.GET.get('q')
    posts = Post.objects.filter(user=request.user.id).order_by('category')
    if category:
        posts = posts.filter(category=category)
    if query:
        posts = posts.filter(Q(title__icontains=query) | Q(content__icontains=query))
    categories = Category.objects.all()
    return render(request, 'home.html',
                  {'posts': posts, 'category': category, 'query': query, 'categories': categories})


@login_required
def create_post(request):
    # import ipdb;
    # ipdb.set_trace()
    if request.method == 'POST':
        form = PostForm(request.POST)
        category_form = CategoryForm(request.POST)  # New category form
        if form.is_valid():
            post = form.save(commit=False)
            post.user = request.user
            post.save()
            category_id = request.POST.get('category')

            if not category_id:
                # No category selected, create a new one
                category = category_form.save()
            else:
                category = Category.objects.get(id=category_id)
            post.category = category  # Associate the post with the category
            post.save()
            return redirect('home')
    else:
        form = PostForm()
        category_form = CategoryForm()  # Empty category form

    return render(request, 'create_post.html', {'form': form, 'category_form': category_form})


@login_required
def delete_post(request, post_id):
    post = get_object_or_404(Post, id=post_id, user=request.user.id)
    if request.method == 'POST':
        post.delete()
        return redirect('home')

    return render(request, 'delete_post.html', {'post': post})


@login_required
def edit_post(request, post_id):
    post = get_object_or_404(Post, id=post_id, user=request.user.id)
    if request.method == 'POST':
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            form.save()
            return redirect('home')
    else:
        form = PostForm(instance=post)
    return render(request, 'edit_post.html', {'form': form})


def post_detail(request, post_id):
    post = get_object_or_404(Post, id=post_id, user=request.user.id)
    return render(request, 'post_detail.html', {'post': post})


@login_required
def create_category(request):
    if request.method == 'POST':
        category_name = request.POST.get('category_name')
        category = Category.objects.create(name=category_name)
        return redirect('blog:create_post')

    return render(request, 'create_category.html')

blog/templates/create_category.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
  <meta charset="UTF-8">
  <title>create category</title>
  <link rel="stylesheet" href="{% static 'blog/style.css' %}">
</head>
<body>

<form method="POST" action="{% url 'blog:create_category' %}">
  {% csrf_token %}

  <!-- Category name field -->
  <label for="category_name">Category Name:</label>
  <input type="text" name="category_name" id="category_name">

  <button type="submit">Create Category</button>
</form>

</body>
</html>

blog/templates/create_post.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <title>Create Post</title>
    <link rel="stylesheet" href="{% static 'blog/style.css' %}">
</head>
<body>
  <h2>Create Post</h2>
<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
    <button><a href="{% url 'blog:create_category' %}">Create New Category</a></button>
    <button type="submit">Create post</button>
</form>
</body>
</html>

blog/templates/delete_post.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{% static 'blog/style.css' %}">
</head>
<body>
<h2>Delete post</h2>
<form method="post">
  {% csrf_token %}
  <button type="submit">Delete</button>
</form>

</body>
</html>

blog/templates/edit_post.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <title>Edit Post</title>
    <link rel="stylesheet" href="{% static 'blog/style.css' %}">
</head>
<body>

<h2>Edit Post</h2>
<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Save changes</button>
</form>

</body>
</html>

blog/templates/home.html
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/html">
{% load static %}
<head>
  <title>Reluxx Blog</title>
  <link rel="stylesheet" href="{% static 'blog/style.css' %}">
</head>
<body>
<center>
  <h1>Hello Reluxx Community</h1>
  <h2>My Posts</h2>

  {% if not user.is_authenticated %}
  <div class="top-right-buttons">
    <button>
      <a href="{% url 'blog:register' %}"  />register </a>
    </button>
        <button>
      <a href="{% url 'blog:login' %}"  />login </a>
    </button>
  </div>
{% endif %}

  <form method="GET">
    {% csrf_token %}
    <input type="text" name="q" placeholder="Search..." value="{{ query }}">
    <select name="category">
      <option value="" {% if not category %}selected{% endif %}>All Categories</option>
      {% for category in categories %}
        <option value="{{ category.pk }}" {% if category.pk == category %}selected{% endif %}>{{ category.name }}</option>
      {% endfor %}
    </select>
    <!-- Create Category button -->
    <button type="submit">Search</button>
  </form>

  <ul>
    {% for post in posts %}
      <li>
        <div class="post-details">
          {{ post.title }} - {{ post.content }} - {{ post.category }}
        </div>
        <div class="post-actions">
          <a href="{% url 'blog:view_post' post.pk %}"><button>View</button></a>
          <a href="{% url 'blog:edit_post' post.pk %}"><button>Edit</button></a>
          <a href="{% url 'blog:delete_post' post.pk %}"><button>Delete</button></a>
        </div>
      </li>
    {% empty %}
      <li>No posts yet.</li>
    {% endfor %}
  </ul>

  <h2>Create your posts here:</h2>
  <button><a href="{% url 'blog:create_post' %}">Create New Post</a></button>

    {% if user.is_authenticated %}
  <div class="top-right-buttons">
    <button>
      <a href="{% url 'blog:logout' %}"  />logout </a>
    </button>
  </div>
{% endif %}
</center>
</body>
</html>

blog/templates/login.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{% static 'blog/style.css' %}">
</head>
<body>
<center>
    <h2>Login</h2>
    {% if error_message %}
     {{ error_message }}
    {% endif %}

    <form method="post">
        {% csrf_token %}
        <label for="username">Username</label>
        <input type="text" name="username" required><br/>
        <label for="password">Password</label>
        <input type="password" name="password" required><br/>
        <button type="submit">login</button>
    </form>
</center>
</body>
</html>

blog/templates/post_detail.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{% static 'blog/style.css' %}">
</head>
<body>
<li>
  <h2>The details of this post:</h2>
  <ul> Title: {{post.title}}</ul>
  <ul> Content: {{post.content}}</ul>
  <ul> Category: {{post.category}}</ul>
  <ul> User: {{post.user}}</ul>
</li>

</body>
</html>

blog/templates/register.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{% static 'blog/style.css' %}">
</head>
<body>
<h2>register</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">register</button>
</form>
</body>
</html>